### ISSUE TITLE
Consider using arduino-RaceChrono library

### ISSUE THREAD

**Issue by timurrrr** [sikrip/suspension-travel-can-device#1]
Here's a link: https://github.com/timurrrr/arduino-RaceChrono

Here's what aollin [said](
https://racechrono.com/forum/discussion/comment/11531/#Comment_11531) about his `racechrono-ble-diy-device` project to me recently:
> Maybe I should deprecate the source code on my repo and point to yours

See also https://github.com/timurrrr/RaceChronoDiyBleDevice

**Comment by sikrip** [comment]
Thanks for the info,  I will consider this lib!
